---
- name: "Change shell for user {{ ansible_facts.env.USER }}, adding in groups."
  user:
    shell: /usr/bin/zsh
    name: "{{ ansible_facts.env.USER }}"
    groups: docker,vboxusers

- name: Enable and start the docker service.
  systemd:
    name: docker
    state: started
    enabled: true
