---

- name: Clone the dotfiles repo.
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ ansible_facts.env.HOME }}/dotfiles"
    recursive: no
    force: yes

- name: Stow the dotfiles.
  shell:
    cmd: stow --target={{ ansible_facts.env.HOME }} */
    chdir: "{{ ansible_facts.env.HOME }}/dotfiles"
  register: stow_result
  changed_when: stow_result.stdout != ""
