---
- name: Update and upgrade pacman packages.
  community.general.pacman:
    update_cache: yes
    upgrade: yes

- name: Install extra packages.
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ pacman_packages }}"
